# Generated by Django 3.1.3 on 2023-06-05 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userprofile_usertype'),
        ('wishlist', '0002_auto_20230605_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='user.userprofile'),
        ),
    ]
