# Generated by Django 3.1.3 on 2023-06-09 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20230604_1654'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wishlist', '0003_auto_20230605_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='wish_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Wish_lists',
            },
        ),
    ]
