# Generated by Django 3.1.3 on 2023-06-23 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0005_auto_20230622_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish_list',
            name='variant',
        ),
    ]
