# Generated by Django 3.2.2 on 2024-08-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0007_auto_20240731_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish_list',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
