BBBBBBB BBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBB XXXXXBBBBBBBB
BBBBB BBBBB XXXXX XXXX BBBBBBBB
BBBBB BBBBBBBB  BBBBBBBB
BBBBB BBBBBBBBBBB  BBBBBBBB

XXXXXXXX XXXXXXXX XXXXX XXXXX XXXXXXXX

XXXXXXX XXXX XXXXXXXXXXX
BBBBB BBBBBBBBBB
XXXX XXX XXXXXXXXX XXXXXXX XXXXX XXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX

XXXXXX
XXXX XXXXXXXXXXXX
BB BBBBBBBB
    BBB BBBBBBB BB BBBBBBBB
    XXXX XXXXXXXXXXXX X XXXXXXXXXXXXX
   XXX  XXXX
     XXXXXXX
    XXXXXX
    BBBBBB
    BBBBB
XXXXXX
XXXX XXX XXX XXXX XXX
BBBBBBBB

BBBBB BBBBB

BB BBBBBBBB
BBB BBBBBBB BB BBBBBBBB
XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
    
XXXXXX
BBBBBB
BBBBB

XXXXXX
XXXXXX
XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
XXXX X
  XXXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXX
X

X X
  XXXXXXXXXXX XXXXXXXXXXX
X

XX XXXXX XXX XXXXXXXXX XX
XXXXXXXXXX X
  XXXXXXXXX XXXXXXXXX
  XXXXXXXXXXXXXX XXXX
  XXXXXXXXXXXXXXXXX XXXXXXXX
  XXXXXXXX XXXX X XXXX XX
X

XX XXXXX XXXXXX XXX XXXX XXXXXXX XX
XXXXXX
XXXX X
  XXXXXX XXXXX
  XXXXXXXX XXXXX
  XXXXXXX XXXXX
  XXXXXXXXXXXXXX XXXX
  XXXXXXX XXX XX
  XXXXXXXX XXXXX
  XXXXXXXX XXXXXXXXXXXXX
  XXXXXXXXXX XXXXX
  XXXXXXXXXXXX XXXXX
  XXXXXXXXXXXXXXXX XXXXX XX XXXXXX XXXXXXXXX XXXX XXXXXXX XX
X

XXXXXXXXXXXX
XXXXXXXXXX X
  XXXXXXXX XX
X

XX XXX XXXXXXXXXXX XXXXXX XX XXX XXXXXXX XXX XXXXXX XXXXXXX XX
XXX X
  XXXXXXXXXXXXXXXXX XXXXXXXX
  XXXXXX XXXXXX
X

XXXXXXXX X
  XXXXXXXXXXXXXXXXX XXXXXXXX
  XXXXXX XXXXXX
X

XXXXXXX X
  XXXXXXXXXXXXXXXXX XXXXXXXX
  XXXXXX XXXXXX
X

XX XXXXX XXX XXXXXX XXXXXX XX
XXXXXXXXXXXXXXXXXX X
  XXXXXXXXXXXXXXXXX XXXXXXXX
  XXXXXX XXXXXX
  XXXXXXX XXXXXXXX
X

XXXXXXXXXXXXXXXXXXXXXXXX X
  XXXXXXXXXXXXXXXXX XXXXXXXX
X

XX XXXXXXXXXX XXXXXX XX
XXXX X
  XXXXXX XXXXX
  XXXXXX XXXX
  XXXXXXX XXXXX
  XXXXXXXX X XXXXX
  XXXXXXXXXXX XXXX
X

XX XXXXX XXXXXX XXXXX XXX XXXXXXX XX
XXXXXXXXXX X
  XXXXXXXX XXX
  XXXXXXXX XXXXXX
  XXXXXX XXXXX
X

XX XXXXXXXX XXXX XX
XXX X
  XXXXXXXXX XXXXXXXXX
  XXXXX XXXX
  XXXXXXXXXX XXXXXXXXXXXXXXXX
  XXXXXXX XXX XXXXX XXXXX
  XXXXXXX XXXXXX
X

XX XXXX XXXXXX XXX XXXXXXXX XXXX XX
XXXXXXXXXXXXX X
  XXXXXXXXX XXXXXXXXX
  XXXX XXXX
  XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
  XXXXXXXXXXXXXXXXX XXXXXXXX
  XXXXXXX XXX XXXXX XXXXX
  XXXXXXXXXXXXXX XXXX
  XXXXXXXX XXX XXXXX
X

XX XXXX XXXX XXXX XX XXXXXX XXX XXXXX XXXXXXX XX
XXXXXXXXXXX X
  XXXXXXXX XXXXX
X

XX XXXXXX XXXXXXXXX XX
XXXXXXXXXXXXXXXXX X
XXXX  XXXXXXXXX XXXXXXXXXXXX
  XXXXXXXXXXX XXXXXXX
  XXXXXXXXXXXXXXXXX XXXXX
  XXXXXXXXXXXXXX XXX XXX XXX XXXX
XXXX  XXXXXXXX XXXX X XXXX XXXXX
X


XX XXXXXXXXXX XXXXXX X XXXX XXX XXXXXX XX XXXX XXXX XXXXX XXXXX XXXX XXX XXX XXXXXXX XXXXX XX XXX XX XXXX XXXXX XXXXXXX XX XXXX XX XXXX XXXXX XX
XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXX X
  XXXX X
    XXXXXX XXXXX
    XXXXXXXXXXX XX
  X
  XX XXXX XXX XXXXXXXX XXXX XX
  XXX X
    XXXXXXXX XXXXX
  X
  XX XXXX XXX XXXXXX XXXX XX XXXXX XXXXXXX XX
  XXXXXXXXXXX X
    XXXXXXXX XXXXXX
    XXXXXXXXXXX XXXXXXX
  X
X
XXXXXXXX
XXXXXXX
XXXXXX

XXXXXXXXXXXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXX
XXXXXXXXXXXXX XXX XXXXXXX XXXXXX XX XXX XXX XXXXXXXXXX XXXXXXX XXXX XXX XXXXXX XX XXXX XXXX XXXXX XXXXX XXXX XXX XXX XXXXXXX XXXXX XX XXX XX XXXX XXXXX XXXXXXX XX XXXX XX XXXX XXXXXXXXXXXXX

XXXX XXXXXXXXXXXXXXXXXX
XXXX  XXXXX XXXXXXXXXX XXXXXXXXXX
    XXXX XXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXX XXXXX XX XXXXXXXXXXXXX

      XXXX XXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXX
XXXX          XXX XXXXXXXXXXXXXXXXXXXXX
          BBBB BBBBBBBBBBBBB
          BBBBBBBBBBBBBBBBBB
          XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXX
        XX XXXXXXBBBBBBBBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBBBX XXXXXXXXX XXXXX
          XX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXXX XXXXXXXX
         XXXX
XXXX        XX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
XXXX          XX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXX XXXX XXXXXXXXXX
XXXX        XXXXXXX
        XX XXXXXXBBBBBBBBBBBBBBBBBB BBBBBBBBX XXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXX
          XXXX XXXXX XXXX XXXXXXX
        XXXX
      XXXXXX

      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXXX XXXX XX XXXXXXXXXXXXX
        XXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXX
          XXXXX XXXXXXXXX XXXXXXXXXXXXXX
              BBBBBBBBBB
              BBB BB BB BBBB
                 FFFFFFFFF XXXXXXXX
                BBBBBB
XXXX            XXXXXXXXXXXXXXXX
XXXX        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
XXXX        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
          XXXXXXX
      XXXXXX

    XXXXXX


XXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXX
    XXXX XXXXXXXXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXX
      XX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXXX
  XXXXXX
XXXXXX

XXXXXXX
XXXXXXX


BBBBBBBB