BBBBBBB BBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBB XXXXXBBBBBBBB
BBBBB BBBBB XXXXXX XXXX BBBBBBBB
BBBBB BBBBBBBB  BBBBBBBB
BBBBB BBBBBBBBBBB  BBBBBBBB

XXXXXXXX XXXXXXXX XXXXX XXXXX XXXXXXXX

XXXXXXX XXXX XXXXXXXXXXX
BBBBB BBBBBBBBBB
XXXX XXX XXXXXXXXX XXXXXXX XXXXX XXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
XXXXXX
XXXX XXX XXX XXXX XXX
BBBBBBBB
BB BBBBBBBB
BBB BBBBBBB BB BBBBBBBB
XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
    
XXXXXX
BBBBBB
BBBBB
BBBBB BBBBBB
XXXXXX
XXXXXXX
XXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXX
X XXXXXXXXXXXX XXXXXXXXXXX

XX XXXXXXXXXX XXXXX XXXXXX XX
XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
  XXXXXX XXXXX
  XXXXXXXX XXXXX
  XXXXXXX XXX X XXXX XX
  XXXXXXXX XXXXXXXXXXXXX
  XXXXXXX XXXXX
  XXXXXXXXXXX XXXXXXXX
X

XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X
  XXXXXXXXXXXXXXXXX XXXXX
  XXXXXXXX XXXXX
X

XX X
  XXXXXXX XXX XXXXX XXXXXXXX
  XXXXXXXXXXXXXX XXXXX
X

XX XXX X XXXXX XXX XXX XXXXXXX XX
XXXXXX X
  XXXXXXXXXXXXXXXXX XXXXXXXX
  XXXXXX XXXXXX
  XXXXXXXX XXXX XXXXX
  XXXXXXX XXX XX
  XXXXXXX XXXXX
  XXXXXXX XXXXXXXX
  XXXXXX XXXXX
  XXXXXXXX XXXX
X

XXXXXXXXXXXX X
  XXXXXXXXXX
X

XX XXXXX XXXXXX XXX XXX XXXXXX XXXXXX XX
XXXXXXXXXX X
  XXXXXXXX XXXX XXXXX
  XXXXXXXXXXXXXXXXX XXXXXXXX
X

XX XXXXX XXXXXX XXX XXXXXX XXXXXXX XXX XXX XX XXXXX XXXXX XX
XXXXXXXXXXX XXXXXXXXXX X
  XXXXXX XXXXX
  XXXXXX XXXX
X

XX XXX XXXXXXX XX XXXXXXXXX XXXXXXXX XX
XXXXXXXXXX X
  XXXXXXXX XXXXX
X

XX XXXXX XXXXXX XX
XXXXXXXXXXXXXXXX X
  XXXXXXXX XXX
  XXXXXX XXXXX
  XXXXXXXX XXXXXX
X

XX XXXXXX XXXXXX XXX XXXXXX XXXXXX XXX XXXXXX XXXXXX XX XXXXX XXXXX XXXXXXX XX
XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXX X
  XXXXXXXXXXX XXXXXXXXXX X
     XXXXXX XXXXX
  X
X
XXXXXXXX




XXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXX
    BBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXX XXXXXXXXX
        XXXXXXXXX XXXX XX XXXX XXXX XX XXXXXX XX XXXXXXX XXX XXXX XXXXXXXXXXXXXXX
        XXXX

        XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXX


        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXX

        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX

        XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXX

        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX

        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX

        XXXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX
        XXXXXXXX

        XXXXX XXXXXXXX XX XXXXXXX XXX XXXXX XX XXX XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX

        XXXX XXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBXXXXXXXXXXX XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXX
    XXXXXX
XXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX
XXXX    BBBBBBBBBBXXX

XXXX    XXXX XXXXXXXXXXXXXXXXXXXXX
XXXX        XXXXXXXXXXXXXXXX
XXXX        XXXXXXXXX XXXX XX XXXX XXXX XX XXXXXX XX XXXXXXXXXXXXXXX
XXXX        XXXXXXX
XXXX        XXX
XXXX        XXX
XXXX        XXX
XXXX        XXX


XXXX        XXXXXXXXXX
XXXX            XXX

XXXX        XXXXXXXXXXX
XXXX        BB BBBBBBBBBBBBBBBXXX
XXXX        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
XXXX        BBBBBXXX
XXXX        BBB BBBBB BB BBBBBBBBBBBBXXX
XXXX        XX XXXXXXXXXXXXX XXXXXXXXXXXX
XXXX        BBBBBBXXX


XXXX        XXXXXXXXXX
XXXX            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX
XXXX        XXXXXXXXXXX

XXXX        XXXXX XXXXXXXX XX XXXXXXX XXX XXXXX XX XXX XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX

XXXX        XXXX XXXXXXXXXXXXXXXXXXXX
XXXX            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
XXXX            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
XXXX        XXXXXXXXX
XXXX    XXXXXXXXX
XXXXXXXXXXXXXX


BBBBBBBB