BBBBBBB BBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBB XXXXXBBBBBBBB
BBBBB BBBBB XXXXX XXXX  BBBBBBBB
BBBBB BBBBBBBB  BBBBBBBB
BBBBB BBBBBBBBBBB  BBBBBBBB

XXXXXXXX XXXXXXXX XXXXX XXXXX XXXXXXXX

XXXXXXX XXXX XXXXXXXXXXX

BBBBB BBBBBBBB
XXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX

      XXXX XXXXXXXXXXXX

        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXX XX
          BBBBBBB BBBBBBBBBBBBBBBBB
        XXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXX XX
          XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXXX
            BB BBBBBBBB
            BBB BBBBBBB BB BBBBBBBB
            XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
              
            XXXXXX
            BBBBBB
            BBBBB

            XXXX
              XXXXXXXXXXX
              XXXXXXXXX XXXXXXXXX
              XXXXXXXX XXXXXXXXX
              XXXXXXXXXXXXXX
              XXXXXXXXXXXXXXX
              XXXXXXXXXXXXX
              XXXXXXXXXXXXXXX
            XXXXX
            XXXXXXXX
            XXXXXXX
            BBB BB BB BBBBBB
            XXXX
              XXX XXXXXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXX XXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXX
            BBBBBB
            XXXXXXXX
          XXXXXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXX XXXXXX XXXXXX  XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
BBBBBBBB