BBBBBBB BBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBB XXXXXBBBBBBBB
BBBBB BBBBB XXXX XXXXXXX  BBBBBBBB
BBBBB BBBBBBBB  BBBBBBBB
BBBBB BBBBBBBBBBB  BBBBBBBB

XXXXXXXX XXXXXXXX XXXXX XXXXX XXXXXXXX

XXXXXXX XXXX XXXXXXXXXXX

BBBBB BBBBBBBBBB
XXXX XXX XXXXXXXXX XXXXXXX XXXXX XXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXX XXXXXXXXXXXX
    XXXXX
XXXXXX
XXXX XXX XXX XXXX XXX
BBBBBBBB
BBBBB BBBBB

XXXXX XXXXXXXXXX
XXXXXX
XXXX  XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
XXXX  XXXXX XXXXXXXXXXXXXXXXXXX
XXXX  XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
XXXX  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXX  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXX  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXX  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX
  XX XXXXXX XXX XXXXXXXX XXXXXXX XXXXXXXXXXXXX XXX XXXXXXX XXXXXXX XX
  XXXXXXX X
    XXXXXXXXXXXXXX XX
    XXXXXXXXXXXXXX XX
  X

  XX XXX XXXXXX XX XXX XXXX XX XXXXXXXX XXX XX XXXX XXXXXXX XX XXXXXXX XX
  XXXXXXXXXXXX XXXXXXXX XXXXXX

  XX XXX XXXX XXXXXXXXXX XXXXX XXX XXXX XXXXXX XX
  XXXXXXXX X
    XXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXX XXXXXXXX
    XXXXXXX XXXXX
  X

  XX XXX XXXXX XXXXXXXXXX XXXXXX XXXXX XXXX XXX XXXX XXXXXXX XX
XXXX  XXXXXX XXXX
XXXX    XXXXXXXXXXXXXXXXX XXXXXXXX
XXXX    XXXXXX XXXXXXXXX
XXXX    XXXXXXXX XXXXXXXX
XXXX  XXXX

  XX XX XXXXX XXXXXXXX XXX XXXXXX XX XXXXXX XXX XXXXXXX XXX XXXX XX
  XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXX X
    XXXXXXXX X
      XXXXXXX XXXXX
      XXXXXXXX XXXXX
    X
    XXXXXXXXXXXX XXXXXXXXXXXXXX
  X
  XXXXXXXX
XXXXXXX
XXXXXX



XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
    XXXX XXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
      XXXXXXXXXXX  XXXXXXX XXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
                        BBBBBBBBBB
                        XXXXXXXXX XXXXXXXXXXXXXXXXXXX
                            
                            
                        XXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                    XXXXXXX


        XXXX
        XXXXXXXXXXXXXXX
        XXX
            BB BBBBBBBB
            BBB BBBBBBB BB BBBBBBBB
        XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXX
            FFFF
        XXXXXX
            BBBBBB
            BBBBB
        XXXX
    XXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXX
          XXXX XXXXXXXXXXXXX
              XXXXXXX XXXXXXXX XXXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXX
        XXXXXXX XXXXX XXXX XXXXXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
XXXXXXXXX XXXXXXXX
XXXXXXXXX XXX

XXXXXXX
XXXXXXX
BBBBBBBB