BBBBBBB BBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBB XXXXXBBBBBBBB
BBBBB BBBBB XXXXX XXXX  BBBBBBBB
BBBBB BBBBBBBB  BBBBBBBB
BBBBB BBBBBBBBBBB  BBBBBBBB

XXXXXXXX XXXXXXXX XXXXX XXXXX XXXXXXXX
BBBBB BBBB
XXXXXXX
X X
  XXXXXXXXXXX XXXXXXXXXXX
X

XXXX X
  XXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXX
X

XXXXXXX X
  XXXXXX XXXXX
  XXXXXX XXXX
  XXXXXXXX XXXX
X

XX XXXXXXXX XXXXXX XXXXXXX XX
XXXXXXXXXXX X
  XXXXXXXX XXX
  XXXXXX XXXXX
  XXXXXXXX XXXXXX
X

XXXXX X
  XXXXXXXXXXXXXXXX XXXXXXXXX
  XXXXXXXXXXXXXXX XX
  XXXXXX XXXXX
  XXXXXXX XXX XXXXX XXXXX
X

XXX XX X
  XXXXXXXXXXX XXXXX
  XXXXXXXX XXXXX
X

XXXXXXXXXXXXXXXXXX X
  XXXXXXXXXXXXXXXXX XXXXXXXX
X
XXX
  XXXXXXXXXXX XXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXXX
  XXXXXX XXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXX
  XXXXXXXXXXXX XXXXX
  XXXXXXXXXXXXXXX XXXXX
  X
XXXXXXXX
BBBBBBBB
XXXXXXX XXXX XXXXXXXXXXX

BBBBB BBBBBBBB
XXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX

      XXXX XXXXXXXXXXXX

        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXX XX
          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
        XXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXX XX
          XXXXXXXX XXXXXXXXXXXXX

          XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXX
            XXXX
              XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXX XXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXX XXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXX XXXXX
            XXXXX
            XXXXXXXX
            XXXXXXX
            BBB BB BB BBBBBBBB
            XXXX
              XXX XXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXX
                  XXXXXXXX XXXXXXXXX
                XXXX
              XXXXX
              XXX XXXXXXXXXXXXXXXXXX XXXXX
              XXX XXXXXXXXXXXXXXXXXX XXXXX
              XXX XXXXXXXXXXXXXXXXXX XXXXX
              XXX XXXXXXXXXXXXXXXXXX XXXXX
              XXX XXXXXXXXXXXXXXXXXX XXXXX
              XXX XXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XX XXXXXX X XXX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX
              XXXXX
            XXXXX
            BBBBBB
            XXXXXXXX
          XXXXXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
XXXX        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXX          XXXXXXXXX XXXXXX XXXXXX  XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXX        XXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
BBBBBBBB