BBBBBBB BBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBB XXXXXBBBBBBBB
BBBBB BBBBB XXXX XXXXX XXXXXXXXXXXX  BBBBBBBB
BBBBB BBBBBBBB  BBBBBBBB
BBBBB BBBBBBBBBBB  BBBBBBBB

XXXXXXXX XXXXXXXX XXXXX XXXXX XXXXXXXX
BBBBB BBBB
XXXXXXX
X X
  XXXXXXXXXXX XXXXXXXXXXX
X

XXXX X
  XXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXX
X

XXXXXXX X
  XXXXXX XXXXX
  XXXXXX XXXX
  XXXXXXXX XXXX
X

XX XXXXXXXX XXXXXX XXXXXXX XX
XXXXXXXXXXX X
  XXXXXXXX XXX
  XXXXXX XXXXX
  XXXXXXXX XXXXXX
X

XXXXX X
  XXXXXXXXXXXXXXXX XXXXXXXXX
  XXXXXXXXXXXXXXX XX
  XXXXXX XXXXX
  XXXXXXX XXX XXXXX XXXXX
X

XXX XX X
  XXXXXXXXXXX XXXXX
  XXXXXXXX XXXXX
X

XXXXXXXXXXXXXXXXXX X
  XXXXXXXXXXXXXXXXX XXXXXXXX
X
XXX
  XXXXXXXXXXX XXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXXX
  XXXXXX XXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXX
  XXXXXXXXXXXX XXXXX
  XXXXXXXXXXXXXXX XXXXX
  X
XXXXXXXX
BBBBBBBB
XXXXXXX XXXX XXXXXXXXXXX

BBBBB BBBBBBBB
XXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX

      XXXX XXXXXXXXXXXX

        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXX XX
          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
        XXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXX XX
XXXX          XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX

                    XXXXXXXXX XXXXXXXX XXXXXXXXX
            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                          XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXX
                            XXXX
                                XXX XXXXXXXXXXXXXXXXXXXX XXXXX
                                XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX
                                XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXX
                                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
                                XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX
                                XXX XXXXXXXXXXXXXXXXXXXXX XXXXX
                                XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
                                XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
                                XXX XXXXXXXXXXXXXXXXXXXXXX XXXXX
                                XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
                            XXXXX
                          XXXXXXXX
                            XXXXXXX
                            BBB BB BB BBBBBBBBBBBBB

                                XXXX
                                  XXX XXXXXXXXXXXXXXXXXX XXXXX
                                    XXX XXXXXXXXXXXXXXXXXX
                                        XX XXXXXXXXXXXXXXXXXX
                                            BB BBBBBBBBBBBBBBBBBBB B B
                                                XXXX XXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXX
                                            BBBB
                                                XXXX XXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXX
                                            BBBBB
                                        XXXX
                                    XXXXX
                                    XXX XXXXXXXXXXXXXXXXXXXXXXX
                                   XXXX    XXXXX
                                    XXX XXXXXXXXXXXXXXXXXX XXXXX
                                    XXX XXXXXXXXXXXXXXXXXX XXXXX
                                    XXX XXXXXXXXXXXXXXXXXX XXXXX
                                    XXX XXXXXXXXXXXXXXXXXX XXXXX
                                    XXX XXXXXXXXXXXXXXXXXX XXXXX
                                    XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXX
                            BBBBBB
                            XXXXXXXX

                        XXXXXXXX

XXXX                    XXXXXXXXX
      XXXXXX
XXXX      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXX        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXX          XXXX XXXXXXXXXXXXXXXXXXXXXX
XXXX            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
XXXX              XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
XXXX            XXXXXXXXX
XXXX          XXXXXXXXX
XXXX          XXXX XXXXXXXXXXXXXXXXXXXXXX
XXXX            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
XXXX          XXXXXXXXX
XXXX        XXXXXXXXX
XXXX        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXX          XXXXXXXXX XXXXXX XXXXXX  XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXX        XXXXXXXXX
XXXX      XXXXXXXXX
    XXXXXX
  XXXXXX
XXXXXX
BBBBBBBB