BBBBBBB BBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBB XXXXXBBBBBBBB
BBBBB BBBBB XXXXX XXXX  BBBBBBBB
BBBBB BBBBBBBB  BBBBBBBB
BBBBB BBBBBBBBBBB  BBBBBBBB
BBBBB BBBB
XXXXXXX
X X
  XXXXXXXXXXX XXXXXXXXXXX
X

XXXX X
  XXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXX
X

XXXXXXX X
  XXXXXX XXXXX
  XXXXXX XXXX
  XXXXXXXX XXXX
X

XX XXXXXXXX XXXXXX XXXXXXX XX
XXXXXXXXXXX X
  XXXXXXXX XXX
  XXXXXX XXXXX
  XXXXXXXX XXXXXX
X

XXXXX X
  XXXXXXXXXXXXXXXX XXXXXXXXX
  XXXXXXXXXXXXXXX XX
  XXXXXX XXXXX
  XXXXXXX XXX XXXXX XXXXX
X

XXX XX X
  XXXXXXXXXXX XXXXX
  XXXXXXXX XXXXX
X

XXXXXXXXXXXXXXXXXX X
  XXXXXXXXXXXXXXXXX XXXXXXXX
X
XXX
  XXXXXXXXXXX XXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXXX
  XXXXXX XXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXX
  XXXXXXXXXXXX XXXXX
  XXXXXXXXXXXXXXX XXXXX
  X
XXXXXXXX
BBBBBBBB
XXXXXXXX XXXXXXXX XXXXX XXXXX XXXXXXXX

XXXXXXX XXXX XXXXXXXXXXX
BBBBB BBBBBBBBBB
XXXX XXX XXXXXXXXX XXXXXXX XXXXX XXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX  XXXX XXXXXXX XXXXXXXXXX
  XXXXX
XXXXXX
XXXX XXX XXX XXXX XXX
BBBBBBBB
BBBBB BBBBBBBB
XXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX

      XXXX XXXXXXXXXXXX

        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXX XX
          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
        XXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXX XX
          XXXX XXXX XXXXX XXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXX
            XXXX
              XXXXXXXXXXX
              XXXXXXXXX XXXXXXXXX
              XXXXXXXX XXXXXXXXX
              XXXXXXXXXXXXXX
              XXXXXXXXXXXXXXX
              XXXXXXXXXXXXX
              XXXXXXXXXXXXXXX
            XXXXX
            XXXXXXXX
            XXXXXXX
            BBB BB BB BBBBBB
            XXXX
              XXX XXXXXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXX XXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            BBBBBB
            XXXXXXXX
          XXXXXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
XXXX        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXX          XXXXXXXXX XXXXXX XXXXXX  XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXX        XXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
BBBBBBBB