BBBBBBB BBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBB XXXXXBBBBBBBB
BBBBB BBBBB XXXX XXXXXXX  BBBBBBBB
BBBBB BBBBBBBB  BBBBBBBB
BBBBB BBBBBBBBBBB  BBBBBBBB

XXXXXXX XXXXXXX XXXXXXXXXXXXXX
BBBB BBBBBBB

BBBBBBBBBBBB BBBB
BBBB BBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBB BBBB BB BBBBBBBB
BBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBB


BBBBB BBBBBBBBBB
XXXX XXX XXXXXXXXX XXXXXXX XXXXX XXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
    XXXXX
XXXXXX
XXXX XXX XXX XXXX XXX
BBBBBBBB
BBBBB BBBBB

XXXXX XXXXXXXXXX
XXXXXX
XXXX  XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
XXXX  XXXXX XXXXXXXXXXXXXXXXXXX
XXXX  XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
XXXX  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXX  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXX  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXX  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX
  XX XXXXXX XXX XXXXXXXX XXXXXXX XXXXXXXXXXXXX XXX XXXXXXX XXXXXXX XX
  XXXXXXX X
    XXXXXXXXXXXXXX XX
    XXXXXXXXXXXXXX XX
  X

  XX XXX XXXXXX XX XXX XXXX XX XXXXXXXX XXX XX XXXX XXXXXXX XX XXXXXXX XX
  XXXXXXXXXXXX XXXXXXXX XXXXXX

  XX XXX XXXX XXXXXXXXXX XXXXX XXX XXXX XXXXXX XX
  XXXXXXXX X
    XXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXX XXXXXXXX
    XXXXXXX XXXXX
  X

  XX XXX XXXXX XXXXXXXXXX XXXXXX XXXXX XXXX XXX XXXX XXXXXXX XX
XXXX  XXXXXX XXXX
XXXX    XXXXXXXXXXXXXXXXX XXXXXXXX
XXXX    XXXXXX XXXXXXXXX
XXXX    XXXXXXXX XXXXXXXX
XXXX  XXXX

  XX XX XXXXX XXXXXXXX XXX XXXXXX XX XXXXXX XXX XXXXXXX XXX XXXX XX
  XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXX X
    XXXXXXXX X
      XXXXXXX XXXXX
      XXXXXXXX XXXXX
    X
    XXXXXXXXXXXX XXXXXXXXXXXXXX
  X
  XX X
  XXXXXXXXXXX XXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXXX
  XXXXXX XXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXX
  XXXXXXXXXXXX XXXXX
  XXXXXXXXXXXXXXX XXXXX
X
  XXXXXXXX
XXXXXXX
XXXXXX

  XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXX
XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
XXXXXX
XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
XXX XXXXXXXXXX XXXXXXXXXXXX
XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX
XXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
XXXXX
XXXXXX
XXXXXX
XXXXXX XXX

XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
    XXXX XXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
      XXXXXXXXXXX XXXXXX
      XXXX

      XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXXX
          XXXX
            XXXXXXXX XXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
        XXXXXXXX
        XXXXXXX
          XXXX
            XXXXXXXX XXXXXXXXXX
            XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXX
            XXXXXXXXXXXXXX
          XXXXX
          XXXX
            XXXXXXXX XXXXXXXXXX
            XXXX XXXXX
            XXXXXXXXXXXXXX
          XXXXX
          XXXX
            XXXXXXXXXXXXXXX
            XXXXXXXXX
            XXXXXXXXX
          XXXXX
          XXXX
            XXXXXXXXXXXXXX
            XXXXXXXXX
            XXXXXXXXX
          XXXXX
          XXXX
            XXXXXXXXXXXXXXXX
            XXXXXXXXX
            XXXXXXXXX
          XXXXX
          XXXX
            XXXXXXXXXXXXX
            XXXXXXXXX
            XXXXXXXXX
          XXXXX
          XXXX
            XXXXXXXXXXXXXXXX
            XXXXXXXXX
            XXXXXXXXX
          XXXXX
          XXXX
            XXXXXXXXXXXXXX
            XXXXXXXXX
            XXXXXXXXX
          XXXXX
          XXXX
            XXXXXXXX XXXXXXXXX
            XXXXXXXXX
            XXXXXXXXX
          XXXXX
        XXXX
            XXXXXXXX XXXXXXXXXX
            XXXXXXXXX
            XXXXXXXXX
          XXXXX
        XXXXXXXX
      XXXXXXXX
      XXXX
      XXXXXXXXX XXXXXXXXX
      XXX
          BB BBBBBBBB
            BBB BBBBBBB BB BBBBBBBB
                XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXX
                FFFF
                XXXXXX
            BBBBBB
        BBBBB
        XXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXX
      XXXX XXXXXXXXXXXXX
        XXXXXXX XXXXXXXX XXXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXX
        XXXXXXX XXXXX XXXX XXXXXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
XXXXXXXXX XXXXXXXX
XXXXXXXXX XXX

XXXXXXX
XXXXXXX
BBBBBBBB