BBBBBBB BBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBB XXXXXBBBBBBBB
BBBBB BBBBB XXXXX XXXX  BBBBBBBB
BBBBB BBBBBBBB  BBBBBBBB
BBBBB BBBBBBBBBBB  BBBBBBBB

XXXXXXXX XXXXXXXX XXXXX XXXXX XXXXXXXX

XXXXXXX XXXX XXXXXXXXXXX
BBBBB BBBBBBBBBB
XXXX XXX XXXXXXXXX XXXXXXX XXXXX XXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
  XXXXX
XXXXXX
XXXX XXX XXX XXXX XXX
BBBBBBBB

BBBBB BBBBBBBB
XXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX

            XXXX XXXXXXXXXXXX
                XXXXX XXXXXXXXX XXXXXXXXXXXXXX
                    BBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXX XX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXX

                            XXXX XXXXXXXXXXXXXXXXXXXXXX
                                XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                            XXXXXX
                            XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX  XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX  XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXX  XXXXXXXX  XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                            XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                                    XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
                                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXX
                            XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXX
                                XXXXXXX  XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXX

                    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXX XX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXX
                                XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                            XXXXXX
                            XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX  XXX XXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXX
                            XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX  XXXXXXXXXXXXX
                            XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX  XXXXXXXXXXXXX
                            XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX  XXXXXXXXXXXXX
                        XXXXXX
                    XXXXXX

                XXXXXXX
            XXXXXX

            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXXX
                XXXX

                    BB BBBBBBBB
                    BBB BBBBBBB BB BBBBBBBB
                    XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                        
                    XXXXXX
                    BBBBBB
                    BBBBB

                    XXXXXXX XXXX XXXXXXXX XXX XX XXXX XXXX XXX XXXXX XXXXXXXXX
                    XXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXX
                    XXXXXXXXX
                XXXXX
                XXXXXXXX
                XXXXXXX
                BBB BB BB BBBBBBBB
                XXXX
                    XXX XXXXXXXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBB  B B
                        XXXX XXXXXX XXXXXXX
                        BBBB
                        XXXX XXXXXX XXXXXXX
                        BBBBB

                    XXXXX
                    XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXX X
                         XXXXXXXXX
                    XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBB BB BBBBBB
                        
                        BBBB
                        
                        BBBBB
                    XXXXXXXXXXXXXX
                    XXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                            
                        XXXXXX
                    XXXXX
                    XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBB BB BBBBBB
                        
                        BBBB
                        
                        BBBBB
                    XXXXXXXXXXXXXX
                    XXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X XXX XXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXX
                    XXXXXXX
                XXXXX
                BBBBBB
                XXXXXXXX
            XXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                        XXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXX XXXXXX XXXXXX  XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB