BBBBBBB BBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBB XXXXXBBBBBBBB
BBBBB BBBBB XXXXX XXXX  BBBBBBBB
BBBBB BBBBBBBB  BBBBBBBB
BBBBB BBBBBBBBBBB  BBBBBBBB

XXXXXXXX XXXXXXXX XXXXX XXXXX XXXXXXXX

XXXXXXX XXXX XXXXXXXXXXX
BBBBB BBBBBBBBBB
XXXX XXX XXXXXXXXX XXXXXXX XXXXX XXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
  XXXXX
XXXXXX
XXXX XXX XXX XXXX XXX
BBBBBBBB

BBBBB BBBBBBBB
XXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX

            XXXX XXXXXXXXXXXX
                XXXXX XXXXXXXXX XXXXXXXXXXXXXX
                    BBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXX XX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXX

                            XXXX XXXXXXXXXXXXXXXXXXXXXX
                                XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                            XXXXXX
                            XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX  XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX  XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXX  XXXXXXXX  XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                            XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                                    XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
                                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXX
                            XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXX
                                XXXXXXX  XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXX

                    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXX XX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXX
                                XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                            XXXXXX
                            XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX  XXX XXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXX
                            XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX  XXXXXXXXXXXXX
                            XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX  XXXXXXXXXXXXX
                            XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX  XXXXXXXXXXXXX
                        XXXXXX
                    XXXXXX

                XXXXXXX
            XXXXXX

            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX

                XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                  XXXXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX
                  XXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXX
                  XXXXXXXXXXXXX
                XXXXX
              XXXXXXXX

                XXXXXXX
                 BBB BB BB BBBBBBBB

                XXXX
                  XXXXXXXXX
                  BB BBBBBBBBBBBBBBBBBBB  B B

                  XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX  XXXXXXXXX
                  BBBB
                  XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
                  BBBBB
                  XXXXX
                    BB BBBBBBBBBBBBBBBBBB BB BBBBBB
                      
                    BBBB
                      
                    BBBBB
                  XXXXX
                  XXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                  XXXXX
                  XXXXX
                  BB BBBBBBBBBBBBBBBBBB BB BBBBBB
                    
                  BBBB
                    
                  BBBBB
                  XXXXX
                  XXXX
XXXX                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXX X XXX XXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXX
                  XXXXX
                XXXXX
              BBBBBB
                XXXXXXXX
            XXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                        XXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXX XXXXXX XXXXXX  XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB