BBBBBBB BBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBB XXXXXBBBBBBBB
BBBBB BBBBB XXXXX XXXXXXXXX  BBBBBBBB
BBBBB BBBBBBBB  BBBBBBBB
BBBBB BBBBBBBBBBB  BBBBBBBB

XXXXXXXX XXXXXXXX XXXXX XXXXX XXXXXXXX
BBBBB BBBB
XXXXXX XXXXXXXXXXXXXXXX
XXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXX
  XXXXXXXXXXXX
  XXXXXXXXXXXX
  XXXXXXXXXXXX XXXXX
  X
XXXXXXXXXX
  XXXXXXXXXXX XXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXXX
  XXXXXX XXXXXXXX
X

XXXXXXXX
BBBBBBBB
XXXXXXX XXXX XXXXXXXXXXX

BBBBB BBBBBBBB
XXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXX XX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXX
              XXXX
                XXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX

              XXXXX
            XXXXXXXX XXX
            XXXXXXX
            XXXX
              XXXXXXXXXXX XXXXXXXXXX
              XXXXXXXXX

            XXXXX
            XXXX
              XXXXXXXXXXXXXXXXX
              XXXXXXXXX

            XXXXX
            XXXX
              XXXXXXXXXXXXXXXX
              XXXXXXXXX

            XXXXX
            XXXX
              XXXXXXXXX XXXXXXXXXXXXX
              XXXXXXXXX

            XXXXX
            XXXX
              XXXXXXXXXXXX XXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXX

            XXXXX
            XXXX
              XXXXXXX XXXXXXXX
              XXXXXXXXXXXXXXXXXXXX

            XXXXX
            XXXXXXXX
          XXXXXXXX

        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXX XX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXX
              XXXX
                XXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX

              XXXXX
            XXXXXXXX XXX
            XXXXXXX
            XXXX
              XXXXXXXXXXXXX
              XXXX XXXXX

            XXXXX
            XXXX
              XXXXXXXXXXXXXXX XXX XXXX XXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

            XXXXX
XXXX            XXXXXXX
XXXX              XXXXXXXXXXXXXXXX
XXXX              XXXXXXXXXXXXXXXXXX

XXXX            XXXXXXXX
            XXXXXXXX
          XXXXXXXX

        XXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXX
      XXXXX XXXX XXXXXBBBBBB BBXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX

    XXXXXX


  XXXXXX
XXXXXX
BBBBBBBB