BBBBBBB BBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBB XXXXXBBBBBBBB
BBBBB BBBBB XXXX XXXX XXXX  BBBBBBBB
BBBBB BBBBBBBB  BBBBBBBB
BBBBB BBBBBBBBBBB  BBBBBBBB

XXXXXXXX XXXXXXXX XXXXX XXXXX XXXXXXXX

XXXXXXX XXXX XXXXXXXXXXX
BBBBB BBBBBBBBBB
XXXX XXX XXXXXXXXX XXXXXXX XXXXX XXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
  XXXXX
XXXXXX
XXXX XXX XXX XXXX XXX
BBBBBBBB
BBBBB BBBBBBBB
  XXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXX    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXX XXXXXXX XXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                  XXXXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX
                  XXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXX
                  XXXXXXXXXXXXX
                XXXXX
              XXXXXXXX
              XXXXXXX

              BBB BB BB BBBBBBBB


                XXXX
                  XXXXXXXXX
                  BB BBBBBBBBBBBBBBBBBBB  B B

                  XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX  XXXXXXXXX
                  BBBB
                  XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
                  BBBBB
                  XXXXX
                    BB BBBBBBBBBBBBBBBBBB BB BBBBBB
                      
                    BBBB
                      
                    BBBBB
                  XXXXX
                  XXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                  XXXXX
                  XXXXX
                  BB BBBBBBBBBBBBBBBBBB BB BBBBBB
                    
                  BBBB
                    
                  BBBBB
                  XXXXX
                  XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXX X XXX XXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX  XXXXXXXXXX
                  XXXXX
                XXXXX

              BBBBBB
              XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXX
                XXXXXXXX XXXXXX XX XXXXXXXXXXX
                XXXX XXXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX

              XXXXX



              XXXXXXXX
            XXXXXXXX

            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                  XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX  XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBXXXXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
BBBBBBBB