BBBBBBB BBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBB XXXXXBBBBBBBB
BBBBB BBBBB XXXX XXXX XXXX  BBBBBBBB
BBBBB BBBBBBBB  BBBBBBBB
BBBBB BBBBBBBBBBB  BBBBBBBB

XXXXXXXX XXXXXXXX XXXXX XXXXX XXXXXXXX

XXXXXXX XXXX XXXXXXXXXXX
BBBBB BBBBBBBBBB
XXXX XXX XXXXXXXXX XXXXXXX XXXXX XXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
  XXXXX
XXXXXX
XXXX XXX XXX XXXX XXX
BBBBBBBB
BBBBB BBBBBBBB
XXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXX
        XXXX

          BB BBBBBBBB
          BBB BBBBBBB BB BBBBBBBB
          XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
            
          XXXXXX
          BBBBBB
          BBBBB

          XXXXXXX XXXX XXXXXXXX XXX XX XXXX XXXXXXXXX
          XXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXX
          XXXXXXXXXXXXXX
        XXXXX
        XXXXXXXX
        XXXXXXX
        BBB BB BB BBBBBBBB
        XXXX
          XXXX
            BB BBBBBBBBBBBBBBBBBBB  B B
            XXXX XXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXX
            BBBB
            XXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX
            BBBBB
          XXXXX
          XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXX X
              XXXXXXXXX
          XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBB BB BBBBBB
            
            BBBB
            
            BBBBB
          XXXXXXXXXXXXXX
          XXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
              
            XXXXXX
          XXXXX
          XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBB BB BBBBBB
            
            BBBB
            
            BBBBB
          XXXXXXXXXXXXXX
          XXXX
            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X XXX XXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXX
          XXXXX
        XXXXX
        BBBBBB
        XXXXXXXX
      XXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXX XXXXXX XXXXXX  XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
BBBBBBBB