# Generated by Django 3.1.3 on 2022-04-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupons',
            options={'verbose_name': 'Coupons Code', 'verbose_name_plural': 'Coupons'},
        ),
        migrations.AlterField(
            model_name='coupons',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
