# Generated by Django 3.1.3 on 2021-05-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_settinglang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settinglang',
            name='lang',
            field=models.CharField(choices=[('EN', 'English'), ('KH', 'Khmer')], max_length=6),
        ),
    ]
