# Generated by Django 3.1.3 on 2021-05-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210524_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='lang',
            field=models.CharField(blank=True, choices=[('EN', 'English'), ('KH', 'Khmer')], max_length=6, null=True),
        ),
    ]
