# Generated by Django 3.1.3 on 2021-06-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_faq_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='status',
        ),
        migrations.AlterField(
            model_name='faq',
            name='lang',
            field=models.CharField(blank=True, choices=[('en', 'English')], max_length=6, null=True),
        ),
        migrations.DeleteModel(
            name='SettingLang',
        ),
    ]
