# Generated by Django 3.1.3 on 2023-12-02 07:15

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210624_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='privacypolicy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='termofservice',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
