# Generated by Django 3.1.3 on 2024-02-04 09:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='958x401 or 960x401', upload_to='uploads/banner')),
                ('name', models.CharField(blank=True, help_text='Your Main Popose for banner, ex:Discount 20%, Sale off, Free Delivery..', max_length=100)),
                ('description', models.CharField(blank=True, help_text='detail about your promotion slide', max_length=300)),
                ('link', models.CharField(blank=True, help_text='link to product or link to vendor product list', max_length=500)),
                ('startdate', models.DateField(blank=True, help_text='Start date to post banner image')),
                ('finishdate', models.DateField(blank=True, help_text='Finish date for promotion')),
                ('status', models.CharField(blank=True, choices=[('Expired', 'Expired'), ('Valid', 'Valid'), ('Invalid', 'Invalid')], max_length=100)),
                ('supportedby', models.CharField(blank=True, help_text='Vendor Name or Admin', max_length=500)),
                ('term', ckeditor.fields.RichTextField(blank=True, help_text='detail about contact vendor with developer on Banner show, design and date post or expire')),
            ],
        ),
        migrations.AlterField(
            model_name='slider',
            name='descriptionslid',
            field=models.CharField(blank=True, help_text='detail about your promotion slide', max_length=300),
        ),
        migrations.AlterField(
            model_name='slider',
            name='finishdate',
            field=models.DateField(blank=True, help_text='Finish date for promotion'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='headerslide',
            field=models.CharField(blank=True, help_text='ex:For Summer, for Holiday.. ', max_length=200),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(help_text='192x550', upload_to='uploads/slider'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='linkslide',
            field=models.CharField(blank=True, help_text='link to product or link to vendor product list', max_length=500),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slideterm',
            field=ckeditor.fields.RichTextField(blank=True, help_text='detail about contact vendor with developer on slide show, design and date post or expire'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='startdate',
            field=models.DateField(blank=True, help_text='Start date to post Slide image'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='statusslide',
            field=models.CharField(blank=True, choices=[('Expired', 'Expired'), ('Valid', 'Valid'), ('Invalid', 'Invalid')], max_length=100),
        ),
        migrations.AlterField(
            model_name='slider',
            name='supportedby',
            field=models.CharField(blank=True, help_text='Vendor Name', max_length=500),
        ),
        migrations.AlterField(
            model_name='slider',
            name='titleslide',
            field=models.CharField(blank=True, help_text='Your Main Popose for slid, ex:Discount 20%, Sale off, Free Delivery..', max_length=100),
        ),
    ]
