# Generated by Django 3.2 on 2024-04-21 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20240421_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlist',
            name='setting',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.setting'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='setting',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.setting'),
            preserve_default=False,
        ),
    ]
