# Generated by Django 3.1.3 on 2023-07-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_auto_20220511_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='address',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='phone',
            new_name='phone1',
        ),
        migrations.AddField(
            model_name='vendor',
            name='address2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='companydetail',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pattern',
            field=models.ImageField(blank=True, upload_to='images/vendors/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone2',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
