# Generated by Django 3.1.3 on 2023-07-21 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_auto_20230721_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name': 'Vendor', 'verbose_name_plural': 'Vendors'},
        ),
    ]
