# Generated by Django 3.1.3 on 2023-07-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_auto_20230721_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(null=True, upload_to='images/vendors/'),
        ),
    ]
