# Generated by Django 3.1.3 on 2023-07-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_auto_20230721_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/vendors/'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='pattern',
            field=models.ImageField(blank=True, null=True, upload_to='images/vendors/'),
        ),
    ]
