# Generated by Django 3.1.3 on 2023-09-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_auto_20230910_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='maplocation',
            field=models.TextField(help_text='Google map passed link', null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='startyear',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
