# Generated by Django 3.2.2 on 2024-08-02 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0011_comment_v'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment_v',
            old_name='comment',
            new_name='comment_v',
        ),
        migrations.RenameField(
            model_name='comment_v',
            old_name='rate',
            new_name='rate_v',
        ),
        migrations.RenameField(
            model_name='comment_v',
            old_name='subject',
            new_name='subject_v',
        ),
    ]
