# Generated by Django 3.2.2 on 2024-08-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0013_alter_vendor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_v',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('True', 'True'), ('False', 'False')], default='True', max_length=10),
        ),
    ]
