# Generated by Django 3.2.2 on 2024-08-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0014_alter_comment_v_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='Followed_by', to='vendors.Vendor'),
        ),
    ]
