# Generated by Django 3.1.3 on 2021-04-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='usernote',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
