# Generated by Django 3.1.3 on 2024-01-28 09:31
# ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userprofile_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribedUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('created_date', models.DateTimeField(default=1, verbose_name='Date created')),
            ],
        ),
    ]
