# Generated by Django 3.2.2 on 2024-07-31 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_subscribedusers_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedusers',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Date created'),
        ),
    ]
