# Generated by Django 3.2.2 on 2024-08-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedusers',
            name='created_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date created'),
        ),
    ]
