# Generated by Django 3.1.3 on 2021-04-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210428_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='userordernote',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
