# Generated by Django 3.1.3 on 2021-06-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_userordernote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='adminnote',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
