# Generated by Django 3.1.3 on 2021-06-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210624_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentinfo',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='paymentstatus',
            field=models.CharField(choices=[('PAID', 'PAID'), ('UNPAID', 'UNPAID')], default='UNPAID', max_length=10),
        ),
    ]
