# Generated by Django 3.1 on 2024-03-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20240318_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalafterdiscount',
            field=models.FloatField(max_length=150, null=True),
        ),
    ]
