# Generated by Django 3.1 on 2024-03-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_totalafterdiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='grandtotalafterdiscount',
            field=models.FloatField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vat10afterdiscount',
            field=models.FloatField(max_length=150, null=True),
        ),
    ]
