# Generated by Django 3.2 on 2024-04-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20240421_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='grandtotal_in_kh_real',
            field=models.FloatField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rate_by_ordered',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
