# Generated by Django 3.2 on 2024-04-29 06:24

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20240421_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            # field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KH', unique=True),
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KH', unique=False),
        ),
    ]
