# Generated by Django 3.2 on 2024-05-02 04:33

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Please input the phone number the used with telegram. EX:012 345 678', max_length=128, region='KH'),
        ),
    ]
