# Generated by Django 3.2 on 2024-06-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_auto_20240623_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='vat10',
            field=models.FloatField(blank=True, max_length=150, null=True),
        ),
    ]
