# Generated by Django 3.1.3 on 2021-05-06 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_vendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
