# Generated by Django 3.1.3 on 2021-06-24 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_categorylang_productlang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlang',
            name='product',
        ),
        migrations.DeleteModel(
            name='CategoryLang',
        ),
        migrations.DeleteModel(
            name='ProductLang',
        ),
    ]
