# Generated by Django 3.2.2 on 2024-08-01 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20240731_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='vendor',
        ),
    ]
