# Generated by Django 3.2.2 on 2024-08-11 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='m_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Market Price or Regular price', max_digits=12),
        ),
        migrations.CreateModel(
            name='Event_timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateTimeField(blank=True, help_text='Please select Furture date and time from now to countdown')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('False', 'False'), ('Expired', 'Expired')], max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
