# Generated by Django 3.2.2 on 2024-08-11 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_event_timer_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_timer',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Please select Furture date and time from now to countdown', null=True),
        ),
        migrations.AlterField(
            model_name='event_timer',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='event_timer',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('False', 'False'), ('Expired', 'Expired')], max_length=10),
        ),
    ]
