# Generated by Django 3.2.2 on 2024-08-12 04:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20240811_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_timer',
            name='create_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event_timer',
            name='end_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Please select Furture date and time from now to countdown', null=True),
        ),
    ]
