# Generated by Django 3.2.2 on 2024-08-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20240812_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_timer',
            name='status',
            field=models.CharField(blank=True, default='False', max_length=10),
        ),
    ]
