# Generated by Django 3.2.2 on 2024-08-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_event_timer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_timer',
            name='create_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='event_timer',
            name='end_date',
            field=models.DateTimeField(auto_now=True, help_text='Please select Furture date and time from now to countdown', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
